--------------------------------------------------------
-- This VHDL file is generated by MyLogic Station

library ieee;
USE ieee.std_logic_1164.all;

entity FND is
	port (
		W : in std_logic ;
		X : in std_logic ;
		Y : in std_logic ;
		Z : in std_logic ;
		A : out std_logic ;
		B : out std_logic ;
		C : out std_logic ;
		D : out std_logic ;
		E : out std_logic ;
		F : out std_logic ;
		G : out std_logic 
	);
end FND;

architecture structural of FND is
	component AND2
		port (
			O : out std_logic ;
			I1 : in std_logic ;
			I0 : in std_logic 
		);
	end component ;
	component AND2B2
		port (
			O : out std_logic ;
			I0 : in std_logic ;
			I1 : in std_logic 
		);
	end component ;
	component OR3B1
		port (
			I1 : in std_logic ;
			I2 : in std_logic ;
			O : out std_logic ;
			I0 : in std_logic 
		);
	end component ;
	component OR4
		port (
			O : out std_logic ;
			I3 : in std_logic ;
			I2 : in std_logic ;
			I1 : in std_logic ;
			I0 : in std_logic 
		);
	end component ;
	component OR5
		port (
			O : out std_logic ;
			I3 : in std_logic ;
			I2 : in std_logic ;
			I1 : in std_logic ;
			I4 : in std_logic ;
			I0 : in std_logic 
		);
	end component ;
	component AND2B1
		port (
			O : out std_logic ;
			I1 : in std_logic ;
			I0 : in std_logic 
		);
	end component ;
	component AND3B1
		port (
			I2 : in std_logic ;
			I1 : in std_logic ;
			O : out std_logic ;
			I0 : in std_logic 
		);
	end component ;
	component OR2
		port (
			I1 : in std_logic ;
			I0 : in std_logic ;
			O : out std_logic 
		);
	end component ;
	component OR3
		port (
			I1 : in std_logic ;
			I2 : in std_logic ;
			I0 : in std_logic ;
			O : out std_logic 
		);
	end component ;

	signal a_B : std_logic;
	signal a_A : std_logic;
	signal I6_O : std_logic;
	signal I7_O : std_logic;
	signal I11_O : std_logic;
	signal I12_O : std_logic;
	signal a_C : std_logic;
	signal a_D : std_logic;
	signal I15_O : std_logic;
	signal I17_O : std_logic;
	signal I18_O : std_logic;
	signal I20_O : std_logic;
	signal I21_O : std_logic;
	signal I22_O : std_logic;
	signal a_E : std_logic;
	signal a_F : std_logic;
	signal I25_O : std_logic;
	signal a_Y : std_logic;
	signal a_X : std_logic;
	signal a_Z : std_logic;
	signal a_G : std_logic;
	signal I26_O : std_logic;
	signal I27_O : std_logic;
	signal I28_O : std_logic;
	signal a_W : std_logic;

	begin
		I6 : AND2
			port map(
				O => I6_O,
				I1 => a_X,
				I0 => a_Z
			);
		I7 : AND2B2
			port map(
				O => I7_O,
				I0 => a_Z,
				I1 => a_X
			);
		I8 : OR3B1
			port map(
				I1 => I12_O,
				I2 => I11_O,
				O => a_B,
				I0 => a_X
			);
		I0 : OR4
			port map(
				O => a_A,
				I3 => a_W,
				I2 => a_Y,
				I1 => I6_O,
				I0 => I7_O
			);
		I11 : AND2B2
			port map(
				O => I11_O,
				I0 => a_Y,
				I1 => a_Z
			);
		I12 : AND2
			port map(
				O => I12_O,
				I1 => a_Z,
				I0 => a_Y
			);
		I13 : OR3B1
			port map(
				I1 => a_X,
				I2 => a_Z,
				O => a_C,
				I0 => a_Y
			);
		I15 : AND2B2
			port map(
				O => I15_O,
				I0 => a_Z,
				I1 => a_X
			);
		I16 : OR5
			port map(
				O => a_D,
				I3 => a_W,
				I2 => I17_O,
				I1 => I18_O,
				I4 => I15_O,
				I0 => I20_O
			);
		I17 : AND2B1
			port map(
				O => I17_O,
				I1 => a_Y,
				I0 => a_X
			);
		I18 : AND3B1
			port map(
				I2 => a_X,
				I1 => a_Z,
				O => I18_O,
				I0 => a_Y
			);
		I20 : AND2B1
			port map(
				O => I20_O,
				I1 => a_Y,
				I0 => a_Z
			);
		I21 : AND2B2
			port map(
				O => I21_O,
				I0 => a_Z,
				I1 => a_X
			);
		I22 : AND2B1
			port map(
				O => I22_O,
				I1 => a_Y,
				I0 => a_Z
			);
		I23 : OR2
			port map(
				I1 => I21_O,
				I0 => I22_O,
				O => a_E
			);
		I24 : OR3
			port map(
				I1 => a_W,
				I2 => a_X,
				I0 => I25_O,
				O => a_F
			);
		I25 : AND2B2
			port map(
				O => I25_O,
				I0 => a_Z,
				I1 => a_Y
			);
		I26 : AND2B1
			port map(
				O => I26_O,
				I1 => a_X,
				I0 => a_Y
			);
		I27 : AND2B1
			port map(
				O => I27_O,
				I1 => a_Y,
				I0 => a_X
			);
		I28 : AND2B1
			port map(
				O => I28_O,
				I1 => a_X,
				I0 => a_Z
			);
		I29 : OR4
			port map(
				O => a_G,
				I3 => I26_O,
				I2 => I27_O,
				I1 => I28_O,
				I0 => a_W
			);
		a_W <= W;
		a_X <= X;
		a_Y <= Y;
		a_Z <= Z;
		A <= a_A;
		B <= a_B;
		C <= a_C;
		D <= a_D;
		E <= a_E;
		F <= a_F;
		G <= a_G;
end structural;

